"""
Report generation — formats a data dict into a markdown report string
and computes the final BUY / HOLD / SELL verdict.
"""


# ── Formatting helpers ────────────────────────────────────────────────────────

def fmt(v, prefix="", suffix="", decimals=2) -> str:
    if v is None:
        return "N/A"
    if isinstance(v, float):
        return f"{prefix}{v:,.{decimals}f}{suffix}"
    if isinstance(v, int):
        return f"{prefix}{v:,}{suffix}"
    return str(v)


def fmt_big(v) -> str:
    if v is None:
        return "N/A"
    if v >= 1e12:
        return f"${v/1e12:.2f}T"
    if v >= 1e9:
        return f"${v/1e9:.2f}B"
    if v >= 1e6:
        return f"${v/1e6:.2f}M"
    return f"${v:,.0f}"


def rsi_label(rsi) -> str:
    if rsi is None:
        return "N/A"
    if rsi < 30:
        return f"{rsi} — OVERSOLD"
    if rsi > 70:
        return f"{rsi} — OVERBOUGHT"
    return f"{rsi} — NEUTRAL"


def vs_sma(price, sma, label) -> str:
    if sma is None:
        return f"{label}: N/A"
    diff = round((price / sma - 1) * 100, 1)
    arrow = "above" if diff > 0 else "below"
    return f"${sma} ({arrow} {abs(diff)}%)"


# ── Verdict ───────────────────────────────────────────────────────────────────

def overall_verdict(d: dict) -> str:
    """
    Combines technical signal, RSI, analyst recommendation, and price-vs-target
    into a final BUY / HOLD / SELL score.
    """
    f = d["fundamentals"]
    scores = []

    tech = d["tech_signal"]
    scores.append({"BULLISH": 1, "BEARISH": -1}.get(tech, 0))

    rsi = d["rsi"]
    if rsi < 30:
        scores.append(1)
    elif rsi > 70:
        scores.append(-1)
    else:
        scores.append(0)

    rec = (f.get("recommendation") or "").lower()
    if rec in ("strong_buy", "buy"):
        scores.append(1)
    elif rec in ("sell", "strong_sell", "underperform"):
        scores.append(-1)
    else:
        scores.append(0)

    target = f.get("analyst_target")
    price  = d["price"]
    if target and price:
        upside = (target / price - 1) * 100
        scores.append(1 if upside > 20 else -1 if upside < 0 else 0)

    avg = sum(scores) / len(scores)
    if avg >= 0.5:
        return "BUY"
    if avg <= -0.5:
        return "SELL"
    return "HOLD"


# ── Markdown report ───────────────────────────────────────────────────────────

def generate_report(d: dict) -> str:
    f       = d["fundamentals"]
    m       = d["macd"]
    bb      = d["bollinger"]
    price   = d["price"]
    verdict = overall_verdict(d)
    target  = f.get("analyst_target")
    upside  = round((target / price - 1) * 100, 1) if target and price else None

    icon = {"BUY": "🟢", "HOLD": "🟡", "SELL": "🔴"}.get(verdict, "⚪")

    lines = [
        f"# {f.get('name', d['ticker'])} ({d['ticker']}) — Stock Analysis",
        f"**Date:** {d['date']} | **Sector:** {f.get('sector', 'N/A')}",
        f"**Generated by:** yfinance + computed quant indicators",
        "",
        "---",
        "",
        f"## {icon} Final Verdict: {verdict}",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Current Price | ${price} |",
        f"| Daily Change | ${d['daily_chg']} ({d['daily_chg_p']}%) |",
        f"| Technical Signal | {d['tech_signal']} |",
        f"| Analyst Consensus | {(f.get('recommendation') or 'N/A').upper()} ({f.get('num_analysts', 'N/A')} analysts) |",
        f"| Analyst Avg Target | {fmt(target, '$')} ({fmt(upside, suffix='% upside') if upside else 'N/A'}) |",
        "",
        "---",
        "",
        "## 1. Technical Analysis",
        "",
        "### Price & Range",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Current Price | ${price} |",
        f"| Prev Close | ${d['prev_close']} |",
        f"| Daily Change | ${d['daily_chg']} ({d['daily_chg_p']}%) |",
        f"| 52-Week High | ${d['52w_high']} |",
        f"| 52-Week Low | ${d['52w_low']} |",
        f"| ATR (14-day) | ${d['atr']} |",
        f"| Avg Volume (30d) | {d['avg_vol_30d']:,} |",
        "",
        "### Returns",
        "| Period | Return |",
        "|--------|--------|",
        f"| 1 Week | {fmt(d['returns'].get('1w'), suffix='%')} |",
        f"| 1 Month | {fmt(d['returns'].get('1m'), suffix='%')} |",
        f"| 3 Month | {fmt(d['returns'].get('3m'), suffix='%')} |",
        "",
        "### Indicators",
        "| Indicator | Value | Signal |",
        "|-----------|-------|--------|",
        f"| RSI (14) | {rsi_label(d['rsi'])} | {'BUY' if d['rsi'] < 30 else 'SELL' if d['rsi'] > 70 else 'NEUTRAL'} |",
        f"| MACD | {m['macd']} (signal: {m['signal']}, hist: {m['histogram']}) | {m['crossover']} |",
        f"| Bollinger %B | {bb['pct_b']}% of band | {'OVERSOLD' if bb['pct_b'] < 20 else 'OVERBOUGHT' if bb['pct_b'] > 80 else 'NORMAL'} |",
        f"| Bollinger Upper | ${bb['upper']} | — |",
        f"| Bollinger Lower | ${bb['lower']} | — |",
        f"| SMA-20 | {vs_sma(price, d['sma20'], 'SMA-20')} | {'BUY' if d['sma20'] and price > d['sma20'] else 'SELL'} |",
        f"| SMA-50 | {vs_sma(price, d['sma50'], 'SMA-50')} | {'BUY' if d['sma50'] and price > d['sma50'] else 'SELL'} |",
        f"| SMA-200 | {vs_sma(price, d['sma200'], 'SMA-200')} | {'BUY' if d['sma200'] and price > d['sma200'] else 'SELL'} |",
        f"| MA Crossover | {d['crossover']} | {'BUY' if d['crossover'] == 'GOLDEN CROSS' else 'SELL'} |",
        f"| **Overall Tech Signal** | **{d['tech_signal']}** | — |",
        "",
        "---",
        "",
        "## 2. Fundamental Analysis",
        "",
        "### Valuation",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Market Cap | {fmt_big(f.get('market_cap'))} |",
        f"| Trailing P/E | {fmt(f.get('pe_trailing'), suffix='x')} |",
        f"| Forward P/E | {fmt(f.get('pe_forward'), suffix='x')} |",
        f"| PEG Ratio | {fmt(f.get('peg'), suffix='x')} |",
        f"| Price/Sales | {fmt(f.get('ps_ratio'), suffix='x')} |",
        f"| Price/Book | {fmt(f.get('pb_ratio'), suffix='x')} |",
        f"| EV/EBITDA | {fmt(f.get('ev_ebitda'), suffix='x')} |",
        f"| Beta | {fmt(f.get('beta'))} |",
        "",
        "### Growth & Earnings",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Revenue (TTM) | {fmt_big(f.get('revenue_ttm'))} |",
        f"| Revenue Growth (YoY) | {fmt(f.get('revenue_growth'), suffix='%')} |",
        f"| Earnings Growth (YoY) | {fmt(f.get('earnings_growth'), suffix='%')} |",
        f"| EPS (TTM) | {fmt(f.get('eps_ttm'), prefix='$')} |",
        f"| EPS (Forward) | {fmt(f.get('eps_forward'), prefix='$')} |",
        "",
        "### Profitability",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Gross Margin | {fmt(f.get('gross_margin'), suffix='%')} |",
        f"| Operating Margin | {fmt(f.get('op_margin'), suffix='%')} |",
        f"| Net Margin | {fmt(f.get('net_margin'), suffix='%')} |",
        f"| ROE | {fmt(f.get('roe'), suffix='%')} |",
        f"| ROA | {fmt(f.get('roa'), suffix='%')} |",
        "",
        "### Balance Sheet & Cash Flow",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total Cash | {fmt_big(f.get('total_cash'))} |",
        f"| Total Debt | {fmt_big(f.get('total_debt'))} |",
        f"| Debt/Equity | {fmt(f.get('de_ratio'), suffix='%')} |",
        f"| Current Ratio | {fmt(f.get('current_ratio'), suffix='x')} |",
        f"| Operating Cash Flow | {fmt_big(f.get('op_cashflow'))} |",
        f"| Free Cash Flow | {fmt_big(f.get('free_cashflow'))} |",
        "",
        "### Dividend",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Dividend Yield | {fmt(f.get('dividend_yield'), suffix='%')} |",
        f"| Payout Ratio | {fmt(f.get('payout_ratio'), suffix='%')} |",
        "",
        "---",
        "",
        "## 3. Analyst Consensus",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Recommendation | {(f.get('recommendation') or 'N/A').upper()} |",
        f"| # Analysts | {f.get('num_analysts', 'N/A')} |",
        f"| Avg Target | {fmt(f.get('analyst_target'), prefix='$')} |",
        f"| Low Target | {fmt(f.get('analyst_low'), prefix='$')} |",
        f"| High Target | {fmt(f.get('analyst_high'), prefix='$')} |",
        f"| Implied Upside | {fmt(upside, suffix='%') if upside is not None else 'N/A'} |",
    ]

    if d["news"]:
        lines += ["", "---", "", "## 4. Recent News", ""]
        for n in d["news"]:
            title = n.get("title", "")
            pub   = n.get("publisher", "")
            if title:
                lines.append(f"- **{title}** *({pub})*")

    lines += [
        "",
        "---",
        "",
        f"*Data: Yahoo Finance via yfinance. Indicators computed from raw OHLCV. {d['date']}. Not financial advice.*",
    ]

    return "\n".join(lines)
